import { model, models, Schema } from "mongoose";

const ProductSchema = new Schema({
  name: String,
  price: { type: Number, default: 0 },
  b2bPrice: { type: Number, default: 0 },
  delivery: { type: Number, default: 15 },
  unit: String,
  brand: String,
  code: { type: String, unique: true },
  length: Number,
  breadth: Number,
  height: Number,
  weight: Number,
  material: String,
  priceTag: [String],
  priceObject: Schema.Types.Mixed,
  category: [String],
  sub: [String],
  subType: [String],
  fBasic: [String],
  fCapacity: [String],
  fColor: [String],
  fType: [String],
  fMaterial: [String],
  fSize: [String],
  fLabel: [String],
  details: [Schema.Types.Mixed],
  shortDescrp: String,
  inBox: String,
  descrp: String,
  isActive: { type: Boolean, default: false },
  qty: { type: Number, default: 0 },
  images: [Schema.Types.Mixed],
  document: String,
  downloadableFile: String,
  printingArea: {
    area1: { url: String, alt: String },
    area2: { url: String, alt: String },
    area3: { url: String, alt: String },
    area4: { url: String, alt: String },
  },
  printSample: { url: String, alt: String },
  commissions: Schema.Types.Mixed,
  reserved: { type: Number, default: 0 },
  meta: {
    title: String,
    description: String,
  },
  related: Schema.Types.Mixed,
  relatedProducts: [{ type: Schema.Types.ObjectId, ref: "Product" }],
  active: {
    b2c: { type: Boolean, default: false },
    b2b: { type: Boolean, default: false },
    shB2c: { type: Boolean, default: false },
    shB2b: { type: Boolean, default: false },
  },
  qtyActive: {
    b2c: { type: Boolean, default: false },
    b2b: { type: Boolean, default: false },
    shB2c: { type: Boolean, default: false },
    shB2b: { type: Boolean, default: false },
  },
  stockText: String,
  originalPrice: Number,
  originalPriceB2b: Number,
});

const Product = models.Product || model("Product", ProductSchema);
export default Product;
